// <auto-generated />
namespace DirectGharPe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetNullableBrandInProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNullableBrandInProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202007170837455_SetNullableBrandInProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
